package com.krishinirnay.core.designsystem.strings

import androidx.compose.runtime.staticCompositionLocalOf

/**
 * Compose-native i18n layer, selected by [com.krishinirnay.core.data.repository.SettingsRepository.language]
 * ("en"/"hi") — see [com.krishinirnay.navigation.AppStringsProvider]. Chosen over the Android
 * resource-locale mechanism (AppCompatDelegate.setApplicationLocales) because this app has no
 * AppCompat dependency and every screen already reads UI state via Compose/StateFlow.
 */
data class AppStrings(
    // Common
    val online: String,
    val offline: String,
    val settings: String,
    val back: String,
    val logOut: String,

    // Risk badge
    val riskLow: String,
    val riskMedium: String,
    val riskHigh: String,
    val riskNotAssessed: String,

    // Relative time
    val timeJustNow: String,
    val timeSecondsAgoTemplate: String,
    val timeMinutesAgoTemplate: String,
    val timeHoursAgoTemplate: String,
    val timeDaysAgoTemplate: String,
    val timeNever: String,

    // Decision engine — recommendation
    val recommendationIrrigateSevere: String,
    val recommendationIrrigateWaterHigh: String,
    val recommendationShadeOrIrrigateHeat: String,
    val recommendationReviewCropHealthHigh: String,
    val recommendationPlanIrrigationSoon: String,
    val recommendationMonitorTemperature: String,
    val recommendationReviewCropHealthModerate: String,
    val recommendationHealthyRange: String,
    val recommendationNotEnoughData: String,

    // Decision engine — reasons
    val reasonSoilMoistureHighTemplate: String,
    val reasonSoilMoistureMediumTemplate: String,
    val reasonSoilMoistureHealthyTemplate: String,
    val reasonModelPredictionTemplate: String,
    val reasonTemperatureHighTemplate: String,
    val reasonTemperatureMediumTemplate: String,
    val reasonTemperatureHealthyTemplate: String,
    val reasonCropHealthNotAssessed: String,
    val reasonCropHealthAssessedTemplate: String,
    val reasonDeviceOffline: String,

    // Bottom navigation
    val navHome: String,
    val navAdvisory: String,
    val navWeather: String,
    val navAlerts: String,
    val navProfile: String,

    // Dashboard
    val dashboardGreeting: String,
    val dashboardOverallRisk: String,
    val dashboardGatheringReading: String,
    val dashboardViewFullAnalysis: String,
    val dashboardWaterStress: String,
    val dashboardHeat: String,
    val dashboardCropHealth: String,
    val dashboardDeviceOnline: String,
    val dashboardDeviceOffline: String,
    val dashboardSyncedTemplate: String,
    val dashboardQuickAccess: String,
    val dashboardQaAdvisory: String,
    val dashboardQaMonitoring: String,
    val dashboardQaSchemes: String,

    // Live Monitoring / Soil & Field Sensors
    val monitoringTitle: String,
    val soilMoisture: String,
    val temperature: String,
    val humidity: String,
    val phLabel: String,
    val lastUpdatedTemplate: String,

    // Crop Health / Disease Detection
    val diseaseDetectionTitle: String,
    val scanLeaf: String,
    val choosePhoto: String,
    val analyzingPhoto: String,
    val confidenceTemplate: String,

    // Alerts
    val alertsTitle: String,
    val alertsEmpty: String,

    // Voice Assistant / Chatbot
    val voiceAssistantTitle: String,
    val chatbotWelcome: String,
    val chatbotPlaceholder: String,
    val chatbotFallback: String,
    val chatbotListen: String,
    val chatbotSpeak: String,
    val chatbotMicPermissionDenied: String,
    val chatbotSend: String,
    val contentDescOpenChatbot: String,
    val chatbotChipWeather: String,
    val chatbotChipSoilMoisture: String,
    val chatbotChipWhatToDo: String,
    val chatbotChipSchemes: String,
    val chatbotWeatherReplyTemplate: String,
    val chatbotSoilMoistureReplyTemplate: String,
    val chatbotSoilStatusDeficient: String,
    val chatbotSoilStatusTrendingLow: String,
    val chatbotSoilStatusHealthy: String,
    val chatbotSoilStatusUnknown: String,
    val chatbotAdviceIrrigateNowTemplate: String,
    val chatbotAdviceIrrigateSoonTemplate: String,
    val chatbotAdviceNoIrrigationNeeded: String,
    val chatbotAdviceNotEnoughData: String,
    val chatbotSchemesReplyTemplate: String,
    val chatbotFallbackHelp: String,

    // Settings
    val settingsDataSource: String,
    val settingsDataSourceDescription: String,
    val settingsLanguage: String,
    val settingsModeMock: String,
    val settingsModeLive: String,
    val settingsLanguageEnglish: String,
    val settingsLanguageHindi: String,

    // Login
    val loginTagline: String,
    val loginEmail: String,
    val loginPassword: String,
    val loginSubmit: String,
    val loginDemoHint: String,

    // Crop Advisory
    val advisoryTitle: String,
    val advisoryAiAdvice: String,
    val advisoryRecommendedTasks: String,
    val advisoryTaskIrrigate: String,
    val advisoryTaskPestControl: String,
    val advisoryTaskFertilizer: String,
    val advisoryTaskSpraySchedule: String,
    val advisoryIrrigateHighTemplate: String,
    val advisoryIrrigateLowTemplate: String,
    val advisoryPestWithDiseaseTemplate: String,
    val advisoryPestElevated: String,
    val advisoryPestNone: String,
    val advisoryFertilizerDetail: String,

    // Weather
    val weatherTitle: String,
    val weatherToday: String,
    val weatherThreeDay: String,
    val weatherSevenDay: String,
    val weatherRainChance: String,
    val weatherWind: String,
    val weatherRainInTemplate: String,

    // Government Schemes
    val schemesTitle: String,
    val schemesSubtitle: String,
    val schemesViewDetails: String,
    val schemesHideDetails: String,
    val schemesEligibilityLabel: String,

    // Profile
    val profileTitle: String,
    val profileMyCrops: String,
    val profileMyFarm: String,
    val profileMyEquipment: String,
    val profileMyDocuments: String,
    val profileFarmSizeTemplate: String,
    val profileNoDocuments: String,
)

val EnglishStrings = AppStrings(
    online = "Online",
    offline = "Offline",
    settings = "Settings",
    back = "Back",
    logOut = "Log Out",

    riskLow = "Low",
    riskMedium = "Medium",
    riskHigh = "High",
    riskNotAssessed = "Not assessed",

    timeJustNow = "just now",
    timeSecondsAgoTemplate = "%d sec ago",
    timeMinutesAgoTemplate = "%d min ago",
    timeHoursAgoTemplate = "%d hr ago",
    timeDaysAgoTemplate = "%d d ago",
    timeNever = "never",

    recommendationIrrigateSevere = "Irrigate immediately — soil moisture is critically low and temperatures are high.",
    recommendationIrrigateWaterHigh = "Irrigate immediately — soil moisture is critically low.",
    recommendationShadeOrIrrigateHeat = "Provide shade or irrigate to offset high temperatures.",
    recommendationReviewCropHealthHigh = "Crop health risk is high — review the latest scan and consider treatment.",
    recommendationPlanIrrigationSoon = "Plan irrigation within the next day — soil moisture is trending low.",
    recommendationMonitorTemperature = "Monitor temperature — conditions are warmer than ideal.",
    recommendationReviewCropHealthModerate = "Keep an eye on crop health — the latest scan shows a moderate concern.",
    recommendationHealthyRange = "Soil moisture and temperature are within a healthy range. No action needed today.",
    recommendationNotEnoughData = "Not enough data yet to make a recommendation.",

    reasonSoilMoistureHighTemplate = "Soil moisture at %.1f%% is critically low",
    reasonSoilMoistureMediumTemplate = "Soil moisture at %.1f%% is trending low",
    reasonSoilMoistureHealthyTemplate = "Soil moisture at %.1f%% is within a healthy range",
    reasonModelPredictionTemplate = "On-device model predicts %s water-stress risk with %d%% confidence",
    reasonTemperatureHighTemplate = "Temperature at %.1f°C is at or above the high-risk threshold",
    reasonTemperatureMediumTemplate = "Temperature at %.1f°C is warmer than ideal",
    reasonTemperatureHealthyTemplate = "Temperature at %.1f°C is steady and within range",
    reasonCropHealthNotAssessed = "Crop health has not been assessed yet — scan a leaf in Crop Health",
    reasonCropHealthAssessedTemplate = "Latest crop scan (%s) shows %s risk",
    reasonDeviceOffline = "Device is offline — showing the last synced reading",

    navHome = "Home",
    navAdvisory = "Advisory",
    navWeather = "Weather",
    navAlerts = "Alerts",
    navProfile = "Profile",

    dashboardGreeting = "Namaste, Farmer!",
    dashboardOverallRisk = "Overall Field Risk",
    dashboardGatheringReading = "Gathering the first reading…",
    dashboardViewFullAnalysis = "View full AI analysis →",
    dashboardWaterStress = "Water Stress",
    dashboardHeat = "Heat",
    dashboardCropHealth = "Crop Health",
    dashboardDeviceOnline = "Device Online",
    dashboardDeviceOffline = "Device Offline",
    dashboardSyncedTemplate = "Synced %s",
    dashboardQuickAccess = "Quick Access",
    dashboardQaAdvisory = "Crop Advisory",
    dashboardQaMonitoring = "Field Sensors",
    dashboardQaSchemes = "Govt. Schemes",

    monitoringTitle = "Live Monitoring",
    soilMoisture = "Soil Moisture",
    temperature = "Temperature",
    humidity = "Humidity",
    phLabel = "pH · Phase 2 sensor",
    lastUpdatedTemplate = "Last updated %s",

    diseaseDetectionTitle = "Disease Detection",
    scanLeaf = "Scan a leaf",
    choosePhoto = "Choose a photo from your gallery",
    analyzingPhoto = "Analyzing your photo…",
    confidenceTemplate = "%d%% confidence",

    alertsTitle = "Alerts",
    alertsEmpty = "No alerts yet — you'll see risk changes and crop scan results here.",

    voiceAssistantTitle = "Voice Assistant",
    chatbotWelcome = "Namaste Kisan, how can I help you today?",
    chatbotPlaceholder = "Ask about your field…",
    chatbotFallback = "Sorry, I couldn't reach the server just now. Please try again in a moment.",
    chatbotListen = "Listen",
    chatbotSpeak = "Speak",
    chatbotMicPermissionDenied = "Microphone permission is needed for voice input.",
    chatbotSend = "Send",
    contentDescOpenChatbot = "Open chatbot",
    chatbotChipWeather = "Weather?",
    chatbotChipSoilMoisture = "Soil moisture?",
    chatbotChipWhatToDo = "What should I do?",
    chatbotChipSchemes = "Schemes?",
    chatbotWeatherReplyTemplate = "Rain chance in the next %s hours is %d%%. Wind speed is %d km/h.",
    chatbotSoilMoistureReplyTemplate = "Your soil moisture is %.1f%% — %s.",
    chatbotSoilStatusDeficient = "Deficient",
    chatbotSoilStatusTrendingLow = "Trending Low",
    chatbotSoilStatusHealthy = "Healthy",
    chatbotSoilStatusUnknown = "Not assessed",
    chatbotAdviceIrrigateNowTemplate = "Irrigate today for about %d minutes.",
    chatbotAdviceIrrigateSoonTemplate = "Plan to irrigate within the next day for about %d minutes.",
    chatbotAdviceNoIrrigationNeeded = "No irrigation needed today — conditions are healthy.",
    chatbotAdviceNotEnoughData = "Not enough data yet — check back after the first reading.",
    chatbotSchemesReplyTemplate = "Based on your farm, these schemes may help: %s",
    chatbotFallbackHelp = "I can help with soil moisture, weather, irrigation advice, and government schemes — tap a suggestion below or ask me about one of those!",

    settingsDataSource = "Data source",
    settingsDataSourceDescription = "Mock Mode is the default — fully offline, evolving demo data. Switch to Live Mode once a real ESP32 device and Firebase project are connected.",
    settingsLanguage = "Language",
    settingsModeMock = "Mock",
    settingsModeLive = "Live",
    settingsLanguageEnglish = "English",
    settingsLanguageHindi = "हिंदी",

    loginTagline = "Smart field monitoring for every farmer",
    loginEmail = "Email",
    loginPassword = "Password",
    loginSubmit = "Log In",
    loginDemoHint = "Using demo? Try demo@krishinirnay.app",

    advisoryTitle = "Crop Advisory",
    advisoryAiAdvice = "AI Advice",
    advisoryRecommendedTasks = "Current Recommendations",
    advisoryTaskIrrigate = "Irrigate",
    advisoryTaskPestControl = "Pest Control",
    advisoryTaskFertilizer = "Fertilizer Dose",
    advisoryTaskSpraySchedule = "Spray Schedule",
    advisoryIrrigateHighTemplate = "Soil moisture is %d%%. Irrigate within 12–24 hours.",
    advisoryIrrigateLowTemplate = "Soil moisture is healthy at %d%%. No irrigation needed today.",
    advisoryPestWithDiseaseTemplate = "Signs of %s detected — apply the recommended treatment.",
    advisoryPestElevated = "Crop health risk is elevated — inspect leaves for pests or disease.",
    advisoryPestNone = "No pest or disease risk detected — keep monitoring weekly.",
    advisoryFertilizerDetail = "Apply the recommended NPK mix for this growth stage.",

    weatherTitle = "Weather Forecast",
    weatherToday = "Today",
    weatherThreeDay = "3 Days",
    weatherSevenDay = "7 Days",
    weatherRainChance = "Chance of Rain",
    weatherWind = "Wind",
    weatherRainInTemplate = "Rain expected in %s hours",

    schemesTitle = "Government Schemes",
    schemesSubtitle = "Schemes suitable for you",
    schemesViewDetails = "View Details",
    schemesHideDetails = "Hide Details",
    schemesEligibilityLabel = "Eligibility",

    profileTitle = "Profile",
    profileMyCrops = "My Crops",
    profileMyFarm = "My Farm",
    profileMyEquipment = "My Equipment (IoT)",
    profileMyDocuments = "My Documents",
    profileFarmSizeTemplate = "%s acres",
    profileNoDocuments = "No documents uploaded yet.",
)

val HindiStrings = AppStrings(
    online = "ऑनलाइन",
    offline = "ऑफ़लाइन",
    settings = "सेटिंग्स",
    back = "वापस",
    logOut = "लॉग आउट",

    riskLow = "कम",
    riskMedium = "मध्यम",
    riskHigh = "उच्च",
    riskNotAssessed = "मूल्यांकन नहीं",

    timeJustNow = "अभी अभी",
    timeSecondsAgoTemplate = "%d सेकंड पहले",
    timeMinutesAgoTemplate = "%d मिनट पहले",
    timeHoursAgoTemplate = "%d घंटे पहले",
    timeDaysAgoTemplate = "%d दिन पहले",
    timeNever = "कभी नहीं",

    recommendationIrrigateSevere = "तुरंत सिंचाई करें — मिट्टी की नमी बेहद कम है और तापमान अधिक है।",
    recommendationIrrigateWaterHigh = "तुरंत सिंचाई करें — मिट्टी की नमी बेहद कम है।",
    recommendationShadeOrIrrigateHeat = "अधिक तापमान की भरपाई के लिए छाया दें या सिंचाई करें।",
    recommendationReviewCropHealthHigh = "फसल स्वास्थ्य जोखिम अधिक है — नवीनतम स्कैन देखें और उपचार पर विचार करें।",
    recommendationPlanIrrigationSoon = "अगले दिन के भीतर सिंचाई की योजना बनाएं — मिट्टी की नमी घट रही है।",
    recommendationMonitorTemperature = "तापमान पर नज़र रखें — स्थितियाँ सामान्य से अधिक गर्म हैं।",
    recommendationReviewCropHealthModerate = "फसल स्वास्थ्य पर नज़र रखें — नवीनतम स्कैन में मध्यम चिंता दिखी है।",
    recommendationHealthyRange = "मिट्टी की नमी और तापमान स्वस्थ सीमा में हैं। आज किसी कार्रवाई की आवश्यकता नहीं है।",
    recommendationNotEnoughData = "अभी सिफारिश करने के लिए पर्याप्त डेटा नहीं है।",

    reasonSoilMoistureHighTemplate = "मिट्टी की नमी %.1f%% पर बेहद कम है",
    reasonSoilMoistureMediumTemplate = "मिट्टी की नमी %.1f%% पर घट रही है",
    reasonSoilMoistureHealthyTemplate = "मिट्टी की नमी %.1f%% पर स्वस्थ सीमा में है",
    reasonModelPredictionTemplate = "ऑन-डिवाइस मॉडल %s जल-तनाव जोखिम का अनुमान %d%% विश्वास के साथ लगाता है",
    reasonTemperatureHighTemplate = "तापमान %.1f°C उच्च-जोखिम सीमा पर या उससे ऊपर है",
    reasonTemperatureMediumTemplate = "तापमान %.1f°C सामान्य से अधिक गर्म है",
    reasonTemperatureHealthyTemplate = "तापमान %.1f°C स्थिर और सीमा के भीतर है",
    reasonCropHealthNotAssessed = "फसल स्वास्थ्य का अभी तक मूल्यांकन नहीं हुआ — रोग पहचान में पत्ती स्कैन करें",
    reasonCropHealthAssessedTemplate = "नवीनतम फसल स्कैन (%s) में %s जोखिम दिखा",
    reasonDeviceOffline = "डिवाइस ऑफ़लाइन है — अंतिम सिंक की गई रीडिंग दिखाई जा रही है",

    navHome = "होम",
    navAdvisory = "सलाह",
    navWeather = "मौसम",
    navAlerts = "अलर्ट",
    navProfile = "प्रोफाइल",

    dashboardGreeting = "नमस्ते, किसान!",
    dashboardOverallRisk = "समग्र खेत जोखिम",
    dashboardGatheringReading = "पहली रीडिंग एकत्र की जा रही है…",
    dashboardViewFullAnalysis = "पूरा AI विश्लेषण देखें →",
    dashboardWaterStress = "जल तनाव",
    dashboardHeat = "गर्मी",
    dashboardCropHealth = "फसल स्वास्थ्य",
    dashboardDeviceOnline = "डिवाइस ऑनलाइन",
    dashboardDeviceOffline = "डिवाइस ऑफ़लाइन",
    dashboardSyncedTemplate = "%s सिंक हुआ",
    dashboardQuickAccess = "जल्दी पहुंच",
    dashboardQaAdvisory = "फसल सलाह",
    dashboardQaMonitoring = "खेत सेंसर",
    dashboardQaSchemes = "सरकारी योजनाएं",

    monitoringTitle = "लाइव मॉनिटरिंग",
    soilMoisture = "मिट्टी की नमी",
    temperature = "तापमान",
    humidity = "आर्द्रता",
    phLabel = "pH · फेज़ 2 सेंसर",
    lastUpdatedTemplate = "%s को अपडेट किया गया",

    diseaseDetectionTitle = "रोग पहचान",
    scanLeaf = "पत्ती स्कैन करें",
    choosePhoto = "गैलरी से फोटो चुनें",
    analyzingPhoto = "आपकी फोटो का विश्लेषण हो रहा है…",
    confidenceTemplate = "%d%% विश्वास",

    alertsTitle = "अलर्ट",
    alertsEmpty = "अभी कोई अलर्ट नहीं — यहां जोखिम में बदलाव और फसल स्कैन परिणाम दिखेंगे।",

    voiceAssistantTitle = "वॉइस असिस्टेंट",
    chatbotWelcome = "नमस्ते किसान, मैं आपकी क्या मदद कर सकता हूं?",
    chatbotPlaceholder = "अपने खेत के बारे में पूछें…",
    chatbotFallback = "क्षमा करें, अभी सर्वर से संपर्क नहीं हो सका। कृपया थोड़ी देर बाद पुनः प्रयास करें।",
    chatbotListen = "सुनें",
    chatbotSpeak = "बोलें",
    chatbotMicPermissionDenied = "आवाज़ इनपुट के लिए माइक्रोफ़ोन अनुमति आवश्यक है।",
    chatbotSend = "भेजें",
    contentDescOpenChatbot = "चैटबॉट खोलें",
    chatbotChipWeather = "मौसम?",
    chatbotChipSoilMoisture = "मिट्टी की नमी?",
    chatbotChipWhatToDo = "मुझे क्या करना चाहिए?",
    chatbotChipSchemes = "योजनाएं?",
    chatbotWeatherReplyTemplate = "अगले %s घंटों में बारिश की संभावना %d%% है। हवा की गति %d किमी/घंटा है।",
    chatbotSoilMoistureReplyTemplate = "आपकी मिट्टी की नमी %.1f%% है — %s।",
    chatbotSoilStatusDeficient = "कम",
    chatbotSoilStatusTrendingLow = "घट रही है",
    chatbotSoilStatusHealthy = "स्वस्थ",
    chatbotSoilStatusUnknown = "मूल्यांकन नहीं",
    chatbotAdviceIrrigateNowTemplate = "आज लगभग %d मिनट सिंचाई करें।",
    chatbotAdviceIrrigateSoonTemplate = "अगले दिन के भीतर लगभग %d मिनट सिंचाई की योजना बनाएं।",
    chatbotAdviceNoIrrigationNeeded = "आज सिंचाई की आवश्यकता नहीं है — स्थितियां स्वस्थ हैं।",
    chatbotAdviceNotEnoughData = "अभी तक पर्याप्त डेटा नहीं है — पहली रीडिंग के बाद फिर से देखें।",
    chatbotSchemesReplyTemplate = "आपके खेत के लिए ये योजनाएं मददगार हो सकती हैं: %s",
    chatbotFallbackHelp = "मैं मिट्टी की नमी, मौसम, सिंचाई सलाह और सरकारी योजनाओं में मदद कर सकता हूं — नीचे दिए सुझाव पर टैप करें या इनमें से किसी के बारे में पूछें!",

    settingsDataSource = "डेटा स्रोत",
    settingsDataSourceDescription = "मॉक मोड डिफ़ॉल्ट है — पूरी तरह ऑफ़लाइन, बदलता डेमो डेटा। असली ESP32 डिवाइस और Firebase प्रोजेक्ट जुड़ने पर लाइव मोड पर स्विच करें।",
    settingsLanguage = "भाषा",
    settingsModeMock = "मॉक",
    settingsModeLive = "लाइव",
    settingsLanguageEnglish = "English",
    settingsLanguageHindi = "हिंदी",

    loginTagline = "हर किसान के लिए स्मार्ट खेत निगरानी",
    loginEmail = "ईमेल",
    loginPassword = "पासवर्ड",
    loginSubmit = "लॉग इन",
    loginDemoHint = "डेमो आज़मा रहे हैं? demo@krishinirnay.app इस्तेमाल करें",

    advisoryTitle = "फसल सलाह",
    advisoryAiAdvice = "AI सलाह",
    advisoryRecommendedTasks = "वर्तमान अनुशंसाएं",
    advisoryTaskIrrigate = "सिंचाई करें",
    advisoryTaskPestControl = "कीट नियंत्रण",
    advisoryTaskFertilizer = "खाद की मात्रा",
    advisoryTaskSpraySchedule = "स्प्रे का शेड्यूल",
    advisoryIrrigateHighTemplate = "मिट्टी की नमी %d%% है। 12–24 घंटों के भीतर सिंचाई करें।",
    advisoryIrrigateLowTemplate = "मिट्टी की नमी %d%% पर स्वस्थ है। आज सिंचाई की आवश्यकता नहीं है।",
    advisoryPestWithDiseaseTemplate = "%s के लक्षण मिले — अनुशंसित उपचार लागू करें।",
    advisoryPestElevated = "फसल स्वास्थ्य जोखिम अधिक है — कीट या रोग के लिए पत्तियों की जांच करें।",
    advisoryPestNone = "कोई कीट या रोग जोखिम नहीं मिला — साप्ताहिक निगरानी जारी रखें।",
    advisoryFertilizerDetail = "इस विकास चरण के लिए अनुशंसित NPK मिश्रण डालें।",

    weatherTitle = "मौसम पूर्वानुमान",
    weatherToday = "आज",
    weatherThreeDay = "3 दिन",
    weatherSevenDay = "7 दिन",
    weatherRainChance = "बारिश की संभावना",
    weatherWind = "हवा",
    weatherRainInTemplate = "अगले %s घंटों में बारिश की संभावना",

    schemesTitle = "सरकारी योजनाएं",
    schemesSubtitle = "आपके लिए उपयुक्त योजनाएं",
    schemesViewDetails = "विवरण देखें",
    schemesHideDetails = "विवरण छुपाएं",
    schemesEligibilityLabel = "पात्रता",

    profileTitle = "प्रोफाइल",
    profileMyCrops = "मेरी फसलें",
    profileMyFarm = "मेरा खेत",
    profileMyEquipment = "मेरे उपकरण (IoT)",
    profileMyDocuments = "मेरे दस्तावेज़",
    profileFarmSizeTemplate = "%s एकड़",
    profileNoDocuments = "अभी तक कोई दस्तावेज़ अपलोड नहीं किया गया।",
)

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }

fun appStringsFor(languageTag: String): AppStrings = if (languageTag == "hi") HindiStrings else EnglishStrings
